// Duo Labs — performance case studies.
// Client names, product names, and ad-level identifiers withheld.
const CASES = {

  cazameeza: {
    industry: "Fashion & Apparel — E-commerce",
    name: "Fashion E-commerce Scale-Up",
    market: "Egypt · Meta Ads + Shopify",
    hook: "Sustained <b>5.73× ROAS</b> across 8+ months on <b>107M+ EGP</b> gross sales.",
    images: ["cazameeza-0.jpg","cazameeza-1.jpg"],
    captions: ["Shopify — 107.32M EGP gross sales, 42.9K orders, 2.57M sessions","Meta Ads Manager — campaign-level performance across 358 campaigns"],
    stats: [{v:"107M+",l:"EGP Gross Sales"},{v:"5.73×",l:"Avg ROAS · 8+ Months"},{v:"42.9K",l:"Orders"},{v:"2.57M",l:"Sessions"}],
    situation: "We inherited a large fashion account that had lost its structure — a clean older naming convention tangled together with newly-created, fragmented campaigns built with no consistent system. ROAS had dropped noticeably before takeover, and the account was spending across hundreds of campaigns with budget spread thin. The brand had strong product quality but no scalable acquisition engine: static photo ads dominated, quality rankings were below average, there was no catalogue infrastructure, and no structured testing framework.",
    strategy: [
      "Ran a <b>full account audit</b> — opportunity score, blocking-error scan, and month-over-month product-line trend analysis — before touching a single campaign, so every decision was diagnostic rather than reactive.",
      "Diagnosed <b>winning vs. declining product lines</b> separately: some lines were declining from genuine demand drop, others purely from creative fatigue. Separating the two prevented killing profitable products that only needed fresh creative.",
      "Rebuilt the account into a <b>structured, scalable system</b> — consolidated fragmented campaigns, standardized naming, and moved winners onto Advantage+ Catalogue structure.",
      "Introduced a <b>structured testing framework</b> so every product got a fair test across multiple creative angles, holding cost-per-purchase as low as possible.",
      "Flagged that the account was running <b>100% bottom-of-funnel</b> with zero top/mid-funnel coverage — a structural CPA risk — and rebuilt funnel coverage with a dedicated cold-audience layer.",
    ],
    results: [
      {v:"107M+",l:"EGP gross sales"},
      {v:"5.73×",l:"average ROAS, sustained 8+ months"},
      {v:"42.9K",l:"total orders"},
      {v:"2.57M",l:"sessions driven"},
      {v:"17.6M+",l:"EGP managed spend across 358 campaigns"},
    ],
    takeaway: "The account never lacked demand — it lacked a system. Once the structure was rebuilt and winners moved onto catalogue architecture with a real testing framework behind them, a 5.73× ROAS held steady for over eight months at scale. Sustaining efficiency while scaling is the hard part; peaking for one month is not.",
  },

  jnya: {
    industry: "Food & Beverage — E-commerce",
    name: "Dates E-commerce — Account Rebuild",
    market: "Egypt · Meta Ads + Easy Orders",
    hook: "<b>6.78× blended ROAS</b> for the quarter — including a full account ban and cold-account rebuild.",
    images: ["jnya-0.jpg","jnya-1.jpg","jnya-2.jpg"],
    captions: ["Easy Orders — 81K visits, 2.32K orders, 2.66M EGP total sales","Ad set-level performance across the quarter","Campaign-level performance summary"],
    stats: [{v:"2.66M",l:"EGP Total Sales"},{v:"6.78×",l:"Blended ROAS"},{v:"2,320+",l:"Orders (+1,094%)"},{v:"8.53×",l:"Peak Month ROAS"}],
    situation: "Before takeover the brand was capped at 3–4× ROAS with no real scaling — spend concentrated on one or two hero products, leaving most of the catalogue untested. Mid-quarter, the ad account was <b>banned entirely</b>, forcing a full system rebuild on a brand-new, cold account during the brand's off-season. That became the real stress test: could the growth survive losing the account it was built on?",
    strategy: [
      "Built <b>full-catalogue testing</b> instead of hero-product-only spend — systematically testing every SKU for creative and audience fit, which surfaced unexpected winners that outperformed the original hero once properly funded.",
      "Ran <b>vertical and horizontal scaling in parallel</b>: raising budget on winners while duplicating into new audiences — budget increases alone slow down, duplication alone fragments the algorithm; both together compound.",
      "Kept <b>6+ creative formats live simultaneously</b> so when one fatigued, others were already warmed and ready to absorb budget — format diversity as ROAS insurance.",
      "When the account was banned, <b>rebuilt the entire system on a new cold account</b> — same testing framework, same winner criteria, same scaling protocol — treating the off-season as the window to rebuild infrastructure rather than pause.",
      "Used the low-traffic off-season month to push <b>CVR higher</b> through better creative and targeting rather than accepting lower volume.",
    ],
    results: [
      {v:"2.66M",l:"EGP total sales (+1,286% YoY)"},
      {v:"2.09M",l:"EGP net revenue (+1,337%)"},
      {v:"6.78×",l:"blended ROAS incl. ban period"},
      {v:"8.53×",l:"peak month ROAS"},
      {v:"4.26%",l:"CVR — off-season, cold account"},
      {v:"6.26×",l:"post-ban ROAS on 23K spend"},
    ],
    takeaway: "The most defensible result here isn't the peak number — it's that the system survived losing its own ad account mid-quarter and kept compounding. That's the difference between an account that performed well and a system that performs regardless of the account.",
  },

  newtech: {
    industry: "Electronics & Smart Home",
    name: "Multi-Category Account Turnaround",
    market: "Kuwait · Meta Ads (ADV+, multi-category)",
    hook: "Took a Kuwaiti electronics account from <b>2.5× to 7×+ ROAS</b> — making Meta the client's #1 sales channel.",
    images: ["newtech-0.jpg","newtech-1.jpg","newtech-2.jpg"],
    captions: ["Aggregate campaign performance — full engagement window","Ad set performance — peak month, ROAS climbing","Ad set performance — earlier month for comparison"],
    stats: [{v:"2.5→7×",l:"ROAS Growth"},{v:"4×",l:"ROAS Floor Held"},{v:"11×+",l:"Peak Ad Set ROAS"},{v:"#1",l:"Sales Channel"}],
    situation: "We took over an account running at <b>~2.5× ROAS</b>. The client had already lost confidence in the platform and was ready to pull budget entirely, convinced Meta simply wasn't right for their category. We made the case to keep testing before writing it off — the platform wasn't the problem, the system running on it was.",
    strategy: [
      "Built a <b>cross-category testing system</b> covering every product category in the catalogue — not just the obvious sellers — so daily sales weren't dependent on one product line.",
      "Applied <b>push & punishment rules</b>: aggressively scaling budget into winning ad sets while cutting underperformers fast, concentrating spend where it actually converted.",
      "Built <b>product bundles</b> specifically to lift AOV, since the average electronics basket in this market had real room to grow beyond single-item purchases.",
      "Ran <b>continuous CVR fixes on the website itself over 3 months</b> — this wasn't just media buying; conversion-side friction was fixed in parallel, because scaling spend into a leaky funnel only inflates CPA.",
    ],
    results: [
      {v:"4×",l:"ROAS floor sustained for the quarter"},
      {v:"7×+",l:"ROAS reached within the quarter"},
      {v:"11×+",l:"peak individual ad set ROAS"},
      {v:"4.60×",l:"blended ROAS across the full window"},
      {v:"#1",l:"Meta became the largest sales channel"},
    ],
    takeaway: "The client's instinct to blame the platform was reasonable at 2.5× — but the real issue was that the account had no system: no structured testing, no AOV strategy, no CVR ownership. Fixing the system, not switching platforms, is what turned Meta into their number-one channel.",
  },

  thebox: {
    industry: "Giftery — E-commerce",
    name: "Giftery Shop — Platform Migration & Full-Catalogue Testing",
    market: "Egypt · Meta Ads + Shopify",
    hook: "Migration plus full-catalogue testing took ROAS from <b>3.5× to 6.8–9×</b>, doubling revenue on the same budget.",
    images: ["thebox-0.jpg","thebox-1.jpg","thebox-2.jpg","thebox-3.jpg"],
    captions: ["Shopify — 326,444 EGP gross sales post-migration","Shopify — second tracked period","Meta Ads — ad set performance","Meta Ads — ad set performance, second view"],
    stats: [{v:"3.5→6.8×",l:"ROAS Lift"},{v:"4.59%",l:"Conversion Rate"},{v:"2×",l:"Revenue, Same Budget"},{v:"800",l:"EGP AOV"}],
    situation: "The brand was running on a legacy website builder with stability and conversion issues, average ROAS stuck around 3.5×, monthly revenue capped at 120K–150K EGP on a fixed 40K EGP ad budget, and no clear break-even benchmark. No amount of ad optimization could fix a broken checkout and tracking foundation.",
    strategy: [
      "<b>Migrated the site to Shopify first</b> — fixing platform-level stability and conversion issues before touching ad spend, because the constraint was the foundation, not the budget.",
      "Reviewed and optimized creative assets per product, and built <b>product bundles</b> to lift AOV.",
      "Built a <b>structured testing system across the entire catalogue</b> — not just known winners — testing audiences, products, and creatives in parallel to find the real scaling headroom.",
      "Moved into a <b>focused optimization phase</b> to squeeze maximum ROAS from the same budget before pushing for scale.",
      "Scaled validated winners while keeping the testing pipeline running on the rest of the catalogue, so the account never became dependent on one or two hero products.",
    ],
    results: [
      {v:"3.5→6.8×",l:"ROAS (up to 9× on winning ad sets)"},
      {v:"4.59%",l:"conversion rate, quarter-to-date"},
      {v:"273–326K",l:"EGP monthly gross sales"},
      {v:"2×",l:"revenue on the same ad spend"},
    ],
    takeaway: "The platform migration was the unlock — no amount of ad optimization fixes a broken checkout and tracking foundation. Once that was solid, the full-catalogue testing system took the account from one good month to a repeatable growth pattern.",
  },

  lamarblue: {
    industry: "Fashion & Apparel — E-commerce",
    name: "Swimwear Scaling — Stock-Wide Testing",
    market: "Egypt · Meta Ads + Shopify",
    hook: "<b>11.4× campaign ROAS</b> while holding efficiency against the prior season through a stock-wide testing system.",
    images: ["lamarblue-0.jpg","lamarblue-1.jpg","lamarblue-2.jpg"],
    captions: ["Shopify — 774.5K EGP total sales, 310 orders","Ad set-level ROAS across the catalogue","Campaign-level performance summary"],
    stats: [{v:"11.4×",l:"Campaign ROAS"},{v:"774K",l:"EGP Monthly Sales"},{v:"310",l:"Orders"},{v:"27.8K",l:"Sessions"}],
    situation: "The client came in on a platform with weak tracking infrastructure — poor Conversions API support, unreliable Purchase events, and no COD support suited to the market. We migrated to Shopify as the foundation fix before any serious scaling. The business is highly seasonal, so most of the year's revenue compresses into a few months, and the prior year showed a steep seasonal drop-off — making ROAS protection through scaling matter more than usual.",
    strategy: [
      "Built a <b>stock-wide testing system</b> — structured testing across the full product catalogue, not just re-running known winners, so every SKU got a fair shot at finding its audience.",
      "This <b>spread performance risk across more products</b> instead of concentrating budget on 2–3 items — the classic failure mode for stock-heavy fashion brands.",
      "Managed the account through <b>live scaling while holding ROAS steady against the same period the previous season</b> — a year-over-year seasonal benchmark, not just month-over-month.",
      "Ran <b>parallel campaign structures</b> (sales-testing, traffic, engagement) to keep top-of-funnel feeding the system while conversion campaigns scaled.",
    ],
    results: [
      {v:"11.4×",l:"campaign-level ROAS"},
      {v:"774.5K",l:"EGP total sales (month)"},
      {v:"310",l:"orders · 27.8K sessions"},
      {v:"Parity",l:"ROAS held vs. prior season while scaling"},
    ],
    takeaway: "For a stock-heavy seasonal brand, over-reliance on a couple of winners is an existential risk. Building a testing system that moves the entire catalogue, while defending ROAS against the prior season rather than an easy month, is what makes the growth durable instead of lucky.",
  },

  sadaf: {
    industry: "Fashion & Apparel — E-commerce",
    name: "Seasonal Swimwear — Cash Flow vs. Stock Distribution",
    market: "UAE · Meta Ads",
    hook: "Same brand, two opposite seasonal strategies — fast cash-flow one season, full-stock distribution the next.",
    images: ["sadaf-0.jpg","sadaf-1.jpg","sadaf-2.jpg"],
    captions: ["Campaign summary across parallel structures","Ad set performance — fast cash-flow season","Ad set performance — second view"],
    stats: [{v:"4.29×",l:"Cash-Flow Season ROAS"},{v:"5.16×",l:"Copy-Winner Campaign"},{v:"5.05×",l:"CBO-Targeted"},{v:"2",l:"Distinct Strategies"}],
    situation: "Swimwear is a hard-stop seasonal category — everything has to sell within a tight window, and unsold stock past season-end is dead capital. Two seasons demanded two opposite strategies depending on the client's actual priority at the time.",
    strategy: [
      "<b>Season 1 (cash flow):</b> the client needed the biggest number, fastest, on the smallest budget. We ran a rapid testing phase to identify the single best-converting product/audience combination, then concentrated budget on that winner under time pressure — optimized purely for speed-to-cash.",
      "<b>Season 2 (stock distribution):</b> we shifted the approach entirely — no offers, budget spread across the full stock from day one, running ADV+ broad, TOF awareness, CBO-targeted, and <b>copy-winner replication campaigns</b> in parallel.",
      "The second structure explicitly <b>trades a lower peak ROAS on any single product for broader stock movement</b> — the KPI became least dead stock at season-end, not highest ROAS.",
    ],
    results: [
      {v:"4.29×",l:"fast cash-flow season ROAS"},
      {v:"4.22×",l:"ADV+ broad campaign"},
      {v:"5.05×",l:"CBO-targeted campaign"},
      {v:"5.16×",l:"copy-winner replication campaign"},
    ],
    takeaway: "Same brand, same seasonal pressure, two opposite correct answers. When speed-to-cash was the priority, concentrating on one winner was right. When protecting margin across the whole stock became the priority, spreading budget across parallel testing and replication structures was the better call — even at a slightly lower peak ROAS.",
  },

  diar: {
    industry: "Fashion & Apparel — Home Wear",
    name: "Home Wear — 30-Day Sprint",
    market: "Egypt · Meta Ads",
    hook: "<b>48.6× ROAS</b> and <b>1.26M EGP</b> in 30 days, while nearly doubling the brand's audience.",
    images: ["diar-0.jpg","diar-1.jpg"],
    captions: ["Sales tracking sheet — 1.26M EGP gross over the 30-day sprint","Ad set-level performance across the sprint"],
    stats: [{v:"1.26M",l:"EGP Gross Sales"},{v:"48.6×",l:"ROAS"},{v:"+99%",l:"Follower Growth"},{v:"1,205",l:"Orders"}],
    situation: "A local home wear brand needed a focused, time-boxed push to scale — a 30-day sprint including 4 days closed for Eid. Sales are tracked manually since orders come through offline and messaging channels rather than e-commerce checkout.",
    strategy: [
      "Ran <b>broad-targeting campaigns at scale</b>, concentrating spend on the highest-engagement ad sets rather than spreading budget thin across many small tests.",
      "<b>Two broad ad sets carried the account</b> — together over 14,500 EGP of the 25,700 EGP total spend, generating the bulk of impressions and engagement.",
      "Focused creative and targeting on driving <b>immediate sales and audience growth simultaneously</b> — engagement-heavy ad sets doubled as top-of-funnel audience building while still tracking to real revenue.",
    ],
    results: [
      {v:"1.26M",l:"EGP gross sales, +50.5% vs. prior quarter average"},
      {v:"48.6×",l:"ROAS on net spend"},
      {v:"1,205",l:"orders · 1,036 EGP AOV"},
      {v:"+7.3K",l:"new followers (+99%)"},
      {v:"119K",l:"EGP peak single day"},
    ],
    takeaway: "Concentrating spend on two high-performing broad ad sets — rather than fragmenting budget across many small tests — delivered both immediate revenue scale and a near-doubling of the owned audience in 30 days.",
  },

  safia: {
    industry: "Fashion & Apparel — Retail",
    name: "Physical Showroom — Online-to-Offline Tracking",
    market: "Egypt · Meta Ads · 2 branches",
    hook: "Built the tracking bridge between ad spend and the in-store register — <b>603K EGP</b> in net sales tracked.",
    images: ["safia-0.jpg","safia-1.jpg","safia-2.jpg"],
    captions: ["Branch-level invoice tracking — monthly totals","Ad set-level messaging performance by area","Ad set-level messaging performance, second view"],
    stats: [{v:"603K",l:"EGP Net Sales"},{v:"25",l:"Ad Sets"},{v:"348",l:"Monthly Invoices"},{v:"2",l:"Branches"}],
    situation: "A 2-branch fashion showroom with combined monthly sales of 300–350K EGP, <b>no previous paid advertising</b>, no audience base, and an unoptimized social presence. The core challenge wasn't creative or budget — there was no measurement bridge between ad spend and actual showroom sales.",
    strategy: [
      "Prepared and optimized the social accounts for paid traffic from a cold start, and produced <b>new AGC/UGC-style creatives</b> suited to performance campaigns rather than pure brand content.",
      "Ran a <b>Messages-first campaign structure</b> — heavy messaging campaigns targeting audiences by branch area alongside Advantage+ profile-visit campaigns — built around how this audience actually shops (DM-based, not checkout-based).",
      "<b>Implemented a sales tracking sheet connecting branch-level invoices to campaign spend</b> — the key infrastructure piece, since without it there was no way to prove paid traffic drove real in-store revenue.",
      "Focused targeting locally around each branch to support both showroom visits and direct DM orders.",
    ],
    results: [
      {v:"603K",l:"EGP total net sales tracked"},
      {v:"178",l:"invoices / 337,999 EGP — Branch A"},
      {v:"170",l:"invoices / 265,878 EGP — Branch B"},
      {v:"25",l:"ad sets, 74.5K EGP spend"},
    ],
    takeaway: "For a business with no e-commerce checkout, the win wasn't creative or targeting — it was building the missing link between ad spend and the in-store register. Once that tracking existed, every other decision had real data behind it instead of guesswork.",
  },

  moist: {
    industry: "Beauty & Cosmetics",
    name: "Skincare New Line Launch",
    market: "Egypt · Meta Ads",
    hook: "<b>9.44× peak ROAS</b> launching a new line by bridging trust from the brand's existing products.",
    images: ["moist-0.jpg","moist-1.jpg","moist-2.jpg"],
    captions: ["Campaign performance summary — 5.51× blended ROAS","Ad set-level results — winning bridge angle at 9.44×","Ad set-level results across other creative angles"],
    stats: [{v:"5.51×",l:"Blended ROAS"},{v:"9.44×",l:"Peak Ad Set"},{v:"154",l:"Purchases"},{v:"101.8K",l:"EGP Revenue"}],
    situation: "The brand launched a <b>new product line</b> and needed to introduce it to an audience that already knew and trusted their existing line. The challenge wasn't cold-audience acquisition — it was linking the new line to the established one in the buyer's mind, so existing trust transferred.",
    strategy: [
      "Built <b>heavy content-type variation</b> — instead of relying on 1–2 creative formats, ran a wide mix (UGC, broad statics, influencer content) simultaneously to find what resonated.",
      "<b>Daily creative rotation at speed</b> — new creatives added and underperformers killed every day rather than on a weekly refresh cycle, keeping the account fed with fresh testing signal.",
      "Ran <b>multiple angles designed to bridge the new line to the old one</b> — leveraging the existing customer base's trust as the unlock for new-line adoption, rather than building trust from zero.",
      "Combined broad targeting with Advantage+ automated targeting in parallel to find pockets of demand across both approaches.",
    ],
    results: [
      {v:"5.51×",l:"blended ROAS"},
      {v:"9.44×",l:"best ad set (trust-bridge angle)"},
      {v:"101.8K",l:"EGP revenue from 18.5K spend"},
      {v:"5.3–6.4×",l:"ROAS on other angles"},
    ],
    takeaway: "For a new line under an established brand, the fastest path to profitable adoption isn't cold-audience creative — it's speed of testing combined with explicit trust-bridging angles that let existing customers self-select into trying the new product.",
  },

  cosmo: {
    industry: "Beauty & Cosmetics",
    name: "Cosmetics — Structured Scaling",
    market: "Egypt · Meta Advantage+ Shopping",
    hook: "Doubled ad spend while holding ROAS above <b>3×</b> through campaign separation, not creative volume.",
    images: ["cosmo-0.jpg","cosmo-1.jpg","cosmo-2.jpg"],
    captions: ["Combined campaign performance view","Campaign performance — scaled spend month","Performance baseline month"],
    stats: [{v:"+106%",l:"Spend Scaled"},{v:"+45%",l:"Revenue Growth"},{v:"4.85×",l:"Baseline ROAS"},{v:"~395",l:"EGP AOV, Held Flat"}],
    situation: "The account needed a clear separation between performance, testing, and retargeting — budget was diluted across campaigns without clear individual objectives, a common cosmetics-vertical issue where CPMs are competitive and inefficient structure directly erodes ROAS.",
    strategy: [
      "<b>Separated campaigns by distinct objective</b>: a dedicated Winners campaign for scaling proven performers, a separate Testing campaign for creatives/audiences, an Advantage+ Shopping campaign, and retargeting — each optimizing toward one clear goal instead of competing for budget internally.",
      "Ran <b>systematic creative and audience testing</b> to isolate winning combinations before committing scale budget.",
      "<b>Scaled budget responsibly</b> — daily monitoring and rapid reallocation on real-time signals to double spend without letting ROAS collapse.",
    ],
    results: [
      {v:"+106%",l:"ad spend, month over month"},
      {v:"+42%",l:"purchase volume"},
      {v:"+45%",l:"total revenue"},
      {v:"~395",l:"EGP AOV held flat through scale-up"},
    ],
    takeaway: "Doubling spend while keeping ROAS above 3× in a competitive cosmetics vertical came down to campaign separation, not creative volume — once winners, tests, and retargeting stopped competing for the same budget pool, scaling became a controlled process instead of a guessing game.",
  },

  bonabella: {
    industry: "Beauty & Cosmetics — Hair Care",
    name: "Hair Care — Channel & Offer Restructuring",
    market: "Egypt · Meta Ads (Conversion + Messages)",
    hook: "Flipped a broken channel-offer structure — <b>4.27× Messages ROAS</b>, the account's best performer.",
    images: ["bonabella-0.jpg","bonabella-1.jpg","bonabella-2.jpg"],
    captions: ["Campaign performance across channels","Ad set performance breakdown","Sales dashboard view"],
    stats: [{v:"4.27×",l:"Messages ROAS"},{v:"3×+",l:"Conversion Ad Sets"},{v:"355K",l:"EGP DM Revenue"},{v:"10.4%",l:"Conv. Rate"}],
    situation: "The account had a structural inefficiency: <b>high-AOV bundle offers were running on the more expensive Messages channel, while the cheaper Conversion channel sold low-AOV single SKUs</b> — the reverse of efficient allocation. This capped blended ROAS regardless of spend. UGC creatives also burned out fast from budget over-concentration on single ad sets — audience exhaustion, not creative fatigue.",
    strategy: [
      "<b>Restructured budget across 3 accounts</b>: 55% to the primary conversion account, 30% to Messages, 15% to a secondary account for testing.",
      "<b>Redistributed UGC creatives across more ad sets</b> to fix audience exhaustion instead of just producing more content.",
      "Pushed <b>bundle offers into the conversion funnel</b> (not just Messages) to lift AOV where it was previously capped by single-SKU-only campaigns.",
      "Tracked revenue <b>cross-referenced against the client's own sales sheet</b> — not just platform-reported numbers — critical for a brand selling across conversion, DM, and marketplace channels simultaneously.",
      "Broke messaging revenue down <b>by actual channel</b> to see which DM channel was really converting.",
    ],
    results: [
      {v:"4.27×",l:"Messages-channel ROAS (vs. 1.98× conversion)"},
      {v:"355K",l:"EGP client-verified DM revenue"},
      {v:"10.4%",l:"conversation-to-order conversion rate"},
      {v:"3×+",l:"conversion ad sets after restructuring"},
      {v:"57%",l:"of DM revenue from the leading channel"},
    ],
    takeaway: "The fix wasn't more budget — it was putting the right offer on the right channel. Once bundles moved into the funnel that actually converts high-AOV purchases, that channel became the account's best ROAS performer. Cross-referencing against real client sales data is what made the insight visible in the first place.",
  },

  hathout: {
    industry: "Food & Beverage — Pastry & Sweets",
    name: "Pastry & Sweets — 9-Day Seasonal Sprint",
    market: "Egypt · Meta Ads · first-ever pixel",
    hook: "<b>558K EGP</b> in 9 days at <b>6×+ ROAS</b>, launching e-commerce from a cold pixel during peak season.",
    images: ["hathout-0.jpg","hathout-1.jpg","hathout-2.jpg"],
    captions: ["Shopify — 558.6K EGP gross sales over the 9-day sprint","Ad set-level performance — seasonal sprint","Sales dashboard, second view"],
    stats: [{v:"558K",l:"EGP Gross Sales"},{v:"6×+",l:"Purchase ROAS"},{v:"559",l:"Orders in 9 Days"},{v:"16×",l:"Best Ad Set ROAS"}],
    situation: "A well-established local pastry brand with strong offline equity and a loyal local base — but <b>zero e-commerce history and a completely cold pixel</b>. The challenge: prove digital sales work during the most competitive seasonal window of the year, against nationally-dominant chains, with no retargeting audiences and no purchase data to optimize against. The first 2–3 days were pure learning phase.",
    strategy: [
      "Built a <b>dual-objective, two-track system</b>: Engagement + Messages campaigns driving offline traffic to branches, running fully separate from Sales campaigns measuring direct e-commerce ROAS — because the brand needed both, and blending them would have made neither measurable.",
      "Ran <b>3 creative formats simultaneously</b> against the same audience, letting real-time ROAS pick the winner and scaling budget daily toward whatever was converting.",
      "<b>Voice-over product reels in Egyptian Arabic</b> emerged as the clear top performer — consistently beating silent reels by 0.5×+ ROAS at the same CPM, since VO builds trust and drives action faster in this market.",
      "The awareness layer reached <b>618K unique accounts at 5.17 EGP CPM</b> pre-season, timed to when purchase intent was forming, building a retargetable owned audience at 1.23 EGP per visit for the next season.",
    ],
    results: [
      {v:"558K",l:"EGP gross sales (Shopify-confirmed)"},
      {v:"6×+",l:"Purchase ROAS across Sales campaigns"},
      {v:"559",l:"total orders in 9 days"},
      {v:"45.1K",l:"store sessions (+29.4%)"},
      {v:"16×",l:"best individual ad set ROAS"},
      {v:"~3 days",l:"branch stock sold out before the peak day"},
    ],
    takeaway: "Launching e-commerce for the first time, in the most competitive week of the year, with a cold pixel and 9 days, isn't usually a recipe for clean numbers. Treating offline traffic and e-commerce as two separate measurable tracks let both channels get optimized correctly — and the branches selling out early is the clearest proof the offline layer was doing real work the ROAS number alone doesn't capture.",
  },

  chunks: {
    industry: "Food & Beverage — Cloud Kitchen",
    name: "Cloud Kitchen — Content-Led Growth",
    market: "Egypt · Meta Ads (supporting) + delivery apps",
    hook: "From <b>50–60K EGP/month</b> to <b>~1.1M EGP/quarter</b> — on just 37.6K EGP of ad spend.",
    images: ["chunks-0.jpg","chunks-1.jpg","chunks-2.jpg","chunks-3.jpg"],
    captions: ["Daily sales tracking — peak month","Daily sales & order channel breakdown","Daily sales & order channel breakdown","Campaign-level performance across the quarter"],
    stats: [{v:"~1.1M",l:"EGP Quarterly Sales"},{v:"6–7×",l:"Monthly Volume Growth"},{v:"37.6K",l:"EGP Total Ad Spend"},{v:"980",l:"Peak Month Orders"}],
    situation: "The client was doing <b>50–60K EGP/month</b> — a small, stagnant cloud-kitchen volume with no real growth engine, relying mostly on delivery-app visibility with minimal brand presence of their own.",
    strategy: [
      "Built a <b>content strategy designed to sell</b> — treating organic/social content as the primary growth driver, not a brand-awareness afterthought. Content was built to convert, not just to get views.",
      "Used <b>paid media in a deliberately supporting role</b> — low relative spend focused on amplifying reach for content that was already converting, rather than carrying growth on ad spend alone.",
      "Ran parallel campaign types (Post Engagement, Messages, Profile Visits) matching the actual order channels the business used — WhatsApp, DMs, phone, delivery app.",
      "Tracked growth across <b>all order channels together</b>, not just paid-attributed sales, because most volume was driven by content and brand awareness rather than direct click-to-purchase.",
    ],
    results: [
      {v:"353K",l:"EGP month one · 911 orders"},
      {v:"399K",l:"EGP peak month · 980 orders"},
      {v:"351K",l:"EGP month three · 906 orders"},
      {v:"~1.1M",l:"EGP quarter, up from 50–60K/month"},
      {v:"37.6K",l:"EGP total ad spend for the quarter"},
    ],
    takeaway: "Not every growth story is a media-buying story. Here the unlock was content that actually sold, with paid media playing a small, deliberate amplification role instead of forcing volume through spend — a far more capital-efficient path for a business without room for heavy ad budgets.",
  },

  yafa: {
    industry: "Food & Beverage — Restaurant",
    name: "Startup Restaurant — Local Brand Growth",
    market: "Egypt · Meta Ads",
    hook: "Zero presence to <b>1,000,000 EGP/month</b> within a quarter, at the lowest CPR in the account's history.",
    images: ["yafa-0.jpg","yafa-1.jpg","yafa-2.jpg"],
    captions: ["Campaign-level performance — 45.7K EGP across 10 campaigns","Ad set-level performance — local area targeting","Cost-per-conversation breakdown"],
    stats: [{v:"1M",l:"EGP Monthly Sales"},{v:"1 Qtr",l:"To Reach It"},{v:"2.43",l:"EGP / Conversation"},{v:"Lowest",l:"CPR On Record"}],
    situation: "A startup restaurant with low brand awareness and no strong social media presence, that needed to build awareness while driving real traffic and orders — from a cold start.",
    strategy: [
      "Managed social campaigns in collaboration with the creative team, using storytelling-based video references for creative direction.",
      "Built a <b>two-layer campaign structure</b>: Awareness (Post Engagement, Profile Visits) to grow reach and followers, and Selling/Messages campaigns to convert that awareness into direct orders.",
      "Ran <b>location-targeted messaging campaigns</b> as a dedicated local-conversion layer alongside the broader awareness push — converting efficiently at neighborhood level while building city-wide recognition.",
    ],
    results: [
      {v:"1M",l:"EGP monthly sales, within a quarter"},
      {v:"2.43",l:"EGP per conversation — local campaign"},
      {v:"45.7K",l:"EGP spend across 10 campaigns"},
      {v:"2.36M+",l:"impressions"},
    ],
    takeaway: "Splitting the strategy into a broad Awareness layer and a hyper-local Messages layer let the account convert efficiently at neighborhood level while building city-wide brand recognition — taking a startup with zero presence to a 1M EGP/month local brand within one quarter.",
  },

};

const INDUSTRIES = [
  {key:"fashion", icon:"🛍️", label:"Fashion & Apparel", cases:["cazameeza","lamarblue","sadaf","diar","safia"]},
  {key:"beauty", icon:"💄", label:"Beauty & Cosmetics", cases:["moist","cosmo","bonabella"]},
  {key:"fnb", icon:"🍽️", label:"Food & Beverage", cases:["jnya","hathout","chunks","yafa"]},
  {key:"giftery", icon:"🎁", label:"Giftery & E-commerce", cases:["thebox"]},
  {key:"electronics", icon:"🔌", label:"Electronics & Smart Home", cases:["newtech"]},
];

const FEATURED = ["cazameeza","jnya","newtech","thebox"];
